// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 AstraLibernis

//! bench/cases.zig — the adversarial corpus: inputs most likely to make zsift's paths
//! disagree. `bench gen adversarial <dir>` writes them (plus EXPECT.tsv); `bench verify`
//! checks each against its expectation. Expectations state the CORRECT behaviour, not
//! what the code does today — a case that fails is a bug to fix, never an expectation
//! to edit.

const std = @import("std");
const Allocator = std.mem.Allocator;

pub const Expect = enum {
    /// Every path yields the scalar parser's field sequence (or the same named error).
    agree,
    /// Not valid strict RFC 4180: the strict paths (pull, push, stream) must each fail
    /// with a named error. The lenient scalar parser may accept it.
    strict_error,
};

pub const Case = struct { name: []const u8, bytes: []const u8, expect: Expect };

const fixed = [_]Case{
    .{ .name = "quoted_newline", .bytes = "a,b\n1,\"x\ny\"\n2,z\n", .expect = .agree },
    .{ .name = "quoted_crlf", .bytes = "a,b\r\n1,\"x\r\ny\"\r\n2,z\r\n", .expect = .agree },
    .{ .name = "escaped_quotes", .bytes = "a,b\n1,\"he said \"\"hi\"\"\"\n2,\"\"\"\"\n", .expect = .agree },
    .{ .name = "quoted_delimiter", .bytes = "a,b\n\"x,y\",\"1,2,3\"\n", .expect = .agree },
    .{ .name = "crlf", .bytes = "a,b\r\n1,2\r\n3,4\r\n", .expect = .agree },
    .{ .name = "lone_cr", .bytes = "a,b\r1,2\r3,4\r", .expect = .agree },
    .{ .name = "no_trailing_newline", .bytes = "a,b\n1,2\n3,4", .expect = .agree },
    .{ .name = "blank_lines", .bytes = "a\n\nb\n\n", .expect = .agree },
    .{ .name = "trailing_delimiter", .bytes = "a,b,\n1,2,\n", .expect = .agree },
    .{ .name = "empty_quoted", .bytes = "a,b\n\"\",x\n,\"\"\n", .expect = .agree },
    .{ .name = "only_header", .bytes = "a,b,c\n", .expect = .agree },
    .{ .name = "empty_input", .bytes = "", .expect = .agree },
    .{ .name = "stray_quote_mid_field", .bytes = "id,item,v\n1,3\" pipe,1.5\n2,plain,2.5\n3,other,3.5\n", .expect = .strict_error },
    .{ .name = "stray_quote_last_field", .bytes = "id,item\n1,6\"\n2,ok\n", .expect = .strict_error },
    .{ .name = "unterminated_at_eof", .bytes = "a,b\n1,\"open\n2,x\n", .expect = .agree },
    .{ .name = "text_after_closing_quote", .bytes = "a,b\n\"x\"y,1\n", .expect = .agree },
    .{ .name = "broken_escape_pair", .bytes = "a\n\"a\"b\"c\"\n", .expect = .agree },
    .{ .name = "quote_reopened_at_eof", .bytes = "a\n\"a\"b\"", .expect = .strict_error },
    .{ .name = "lone_quote_eof_unquoted", .bytes = "a,b\"", .expect = .strict_error },
    // Real data does this: a seconds/inch mark in an unquoted field (coordinates,
    // screen sizes). Not RFC 4180; the lenient scalar parser keeps it as text.
    .{ .name = "seconds_mark_in_coordinates", .bytes = "phone,location,city\n555,37 36'37.8\"N 121 2'17.9\"W,Modesto\n", .expect = .strict_error },
    .{ .name = "stray_then_real_quoted", .bytes = "id,x\n1,3\" pipe\n2,\"q\"\n3,z\n", .expect = .strict_error },
};

/// Every case, fixed and generated. Generated bytes are owned by `alloc`.
pub fn all(alloc: Allocator) ![]Case {
    var out: std.ArrayList(Case) = .empty;
    try out.appendSlice(alloc, &fixed);
    try out.append(alloc, .{ .name = "wide_600_columns", .bytes = try wide(alloc, 600, 3), .expect = .agree });
    try out.append(alloc, .{ .name = "huge_quoted_field_40k", .bytes = try huge(alloc, 40 * 1024), .expect = .agree });
    try out.append(alloc, .{ .name = "chunk_straddle", .bytes = try straddle(alloc), .expect = .agree });
    for ([_]usize{ 62, 63, 64, 65 }) |at| {
        try out.append(alloc, .{ .name = try std.fmt.allocPrint(alloc, "stray_quote_at_{d}", .{at}), .bytes = try strayAt(alloc, at), .expect = .strict_error });
    }
    return out.toOwnedSlice(alloc);
}

/// `cols` columns × `rows` data rows of small integers, plus a header.
fn wide(alloc: Allocator, cols: usize, rows: usize) ![]u8 {
    var b: std.ArrayList(u8) = .empty;
    var buf: [32]u8 = undefined;
    for (0..rows + 1) |r| {
        for (0..cols) |c| {
            if (c > 0) try b.append(alloc, ',');
            const s = if (r == 0) try std.fmt.bufPrint(&buf, "c{d}", .{c}) else try std.fmt.bufPrint(&buf, "{d}", .{r * cols + c});
            try b.appendSlice(alloc, s);
        }
        try b.append(alloc, '\n');
    }
    return b.toOwnedSlice(alloc);
}

/// One quoted field of `n` bytes with an escaped quote and a newline in the middle.
fn huge(alloc: Allocator, n: usize) ![]u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(alloc, "id,blob\n1,\"");
    for (0..n) |i| {
        if (i == n / 2) {
            try b.appendSlice(alloc, "\"\"\n");
        } else try b.append(alloc, 'a' + @as(u8, @intCast(i % 26)));
    }
    try b.appendSlice(alloc, "\"\n2,end\n");
    return b.toOwnedSlice(alloc);
}

/// Quotes, escaped quotes, delimiters and newlines placed on every offset around the
/// SIMD chunk boundaries (64 bytes), where the in-quote carry crosses chunks.
fn straddle(alloc: Allocator) ![]u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(alloc, "pad,q,tail\n");
    for (40..140) |pad| {
        for (0..pad) |_| try b.append(alloc, 'p');
        try b.appendSlice(alloc, ",\"a\"\"b,c\nd\",t\n");
    }
    return b.toOwnedSlice(alloc);
}

/// Clean rows with one stray quote placed at byte `at` of the input, so it lands on
/// either side of the first 64-byte chunk boundary.
fn strayAt(alloc: Allocator, at: usize) ![]u8 {
    var b: std.ArrayList(u8) = .empty;
    try b.appendSlice(alloc, "a,b\n");
    while (b.items.len < 200) try b.appendSlice(alloc, "xxxxxxxxxx,yyyyyyyyyy\n");
    b.items[at] = '"';
    return b.toOwnedSlice(alloc);
}
